hotel/firstpage/urls.py
from django.urls import path
from . import views

app_name = "firstpage"
urlpatterns = [
    path('',views.index,name="index"), 
    path('home/',views.index1,name="index1"),
    path('course/',views.course,name="course"),
    path('admission/',views.admn,name="admission"),
    path('fee/',views.fees,name="fee"),
    path('list/',views.lists,name="list"),

    path('fee_list/',views.feeList,name="feeList"),

    path('employee_corner/', views.employeeCorner, name='employeeCorner'),
    path('employee_attendance/', views.employeeAttendance, name='employeeAttendance'),


    # api
    path('get_student_by_roll_no', views.getStudentByRollNo, name='getStudentByRollNo'),
    path('get_receipt', views.getReceipt, name='getReceipt'),
    path('search_fee', views.searchFee, name='searchFee'),
    path('update_student', views.updateStudent, name='updateStudent'),
    path('delete_student', views.deleteStudent, name='deleteStudent'),
    path('search_student', views.searchStudent, name='searchStudent'),


    path('add_employee', views.addEmployee, name='addEmployee'),
    path('update_employee', views.updateEmployee, name='updateEmployee'),
    path('delete_employee', views.deleteEmployee, name='deleteEmployee'),
    path('search_employee', views.searchEmployee, name='searchEmployee'),

    path('getEmployeeAttendance', views.getEmployeeAttendance, name='getEmployeeAttendance'),

    path('update_employee_attendance', views.updateEmployeeAttendance, name='updateEmployeeAttendance'),
    path('delete_employee_attendance', views.deleteEmployeeAttendance, name='deleteEmployeeAttendance'),
    
    
    path('getReceiptHTML', views.getReceiptHTML, name='getReceiptHTML'),


    path('downloads/', views.downloads, name='downloads'),
    path('new_updates/', views.new_updates, name='new_updates'),


    path('add_new_update', views.add_new_update, name='add_new_update'),
    path('update_new_update', views.update_new_update, name='update_new_update'),
    path('delete_new_update', views.delete_new_update, name='delete_new_update'),


    path('logout/', views.logout_view, name='logout'),

    
]

hotel/hotel/urls.py

from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("firstpage.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/firstpage/models.py
from django.db import models

class Student(models.Model):
    rollnumber = models.AutoField(primary_key=True)
    pfp = models.ImageField(upload_to='images/')
    fullname = models.CharField(max_length=400, default=None, null=False)
    dob = models.DateField()
    email = models.EmailField(unique=True)
    mobile_number = models.IntegerField()
    gender = models.CharField(max_length=200)
    fathername = models.TextField()
    address = models.TextField()
    class10_details = models.JSONField()
    class12_details = models.JSONField()
    graduation_details = models.JSONField()
    masters_details = models.JSONField()
    courses_applied = models.JSONField()
    enrollment_date = models.DateField(auto_now_add=True)

class Fee(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='fee')
    
    receipt_number = models.IntegerField()
    fee_amount = models.IntegerField()
    deposit_date = models.DateField()


class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    pfp = models.ImageField(upload_to='images/')
    fullname = models.CharField(max_length=400, default=None, null=False)
    dob = models.DateField()
    email = models.EmailField(unique=True)
    mobile_number = models.IntegerField()
    gender = models.CharField(max_length=200)
    address = models.TextField()
    class10_details = models.JSONField()
    class12_details = models.JSONField()
    graduation_details = models.JSONField()
    masters_details = models.JSONField()
    joining_date = models.DateField()


class EmployeeAttendance(models.Model):
    id = models.AutoField(primary_key=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.CharField(max_length=200)
    remarks = models.CharField(max_length=200)


class NewUpdate(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

hotel/firstpage/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from datetime import datetime
from .models import Student, Fee, Employee, EmployeeAttendance, NewUpdate

from django.http import JsonResponse
from .serializers import StudentSerializer, FeeSerializer, EmployeeSerializer, EmployeeAttendanceSerializer, NewUpdateSerializer

from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers.json import DjangoJSONEncoder
import json

from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML

from django.conf import settings

import inflect

import os

from django.contrib.auth.decorators import login_required

from django.contrib.auth import login, logout, authenticate


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return redirect(reverse('home:index1'))
    if request.method=='POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect(reverse('firstpage:index1'))

    my_template="login.html"
    return render(request,my_template)

@login_required
def index1(request):
    my_template="home.html"
    return render(request,my_template)

@login_required
def course(request):
    my_template = "courses.html"
    return render(request,my_template)

@login_required
def admn(request):
    if request.method=='POST':
        dob = request.POST['dob']

        class10_details = {
            "board": request.POST['board_x'],
            "percentage": request.POST['percentage_x'],
            "year_of_passing": request.POST['year_x']
        }
        class12_details = {
            "board": request.POST['board_xii'],
            "percentage": request.POST['percentage_xii'],
            "year_of_passing": request.POST['year_xii']
        }
        graduation_details = {
            "board": request.POST['board_graduation'],
            "percentage": request.POST['percentage_graduation'],
            "year_of_passing": request.POST['year_graduation']
        }
        masters_details = {
            "board": request.POST['board_masters'],
            "percentage": request.POST['percentage_masters'],
            "year_of_passing": request.POST['year_masters']
        }

        courses_applied = request.POST.getlist('courses')

        if len(request.FILES)>0:
            student = Student(fullname=request.POST['full_name'], dob=dob, email=request.POST['email'], mobile_number=request.POST['mobile'], gender=request.POST['gender'], address=request.POST['address'], fathername=request.POST['father_name'], class10_details=class10_details, class12_details=class12_details, graduation_details=graduation_details, masters_details=masters_details, pfp=request.FILES['photo'], courses_applied=courses_applied)
            student.save()

        else:
            student = Student(fullname=request.POST['full_name'], dob=dob, email=request.POST['email'], mobile_number=request.POST['mobile'], gender=request.POST['gender'], address=request.POST['address'], fathername=request.POST['father_name'], class10_details=class10_details, class12_details=class12_details, graduation_details=graduation_details, masters_details=masters_details, courses_applied=courses_applied)
            student.save()
        
    my_template = "admission.html"
    return render(request,my_template)

@login_required
def fees(request):
    if request.method == 'POST':
        student = Student.objects.get(rollnumber=request.POST['roll_number'])

        receipt_number = 1600
        if Fee.objects.count()>0:
            receipt_number = Fee.objects.last().receipt_number + 1

        fee = Fee(student=student, receipt_number=receipt_number, fee_amount=request.POST['fee_amount'], deposit_date=request.POST['deposit_date'])
        fee.save()

    my_template = "Fee.html"
    return render(request,my_template)

@login_required
def lists(request):
    students = Student.objects.all().order_by('-enrollment_date').prefetch_related('fee')
    serializer = StudentSerializer(students, many=True)

    serialized_json = json.dumps(serializer.data, cls=DjangoJSONEncoder)
    

    my_template = "list_of_all_st.html"
    context = {
        'students': serialized_json
    }
    return render(request,my_template, context)

@login_required
def feeList(request):
    fee_list = Fee.objects.all().order_by('-deposit_date')
    serializer = FeeSerializer(fee_list, many=True)

    serialized_json = json.dumps(serializer.data, cls=DjangoJSONEncoder)


    my_template = "fee_detail_list.html"
    context = {
        'fee_list': serialized_json,
    }
    return render(request,my_template, context)


@login_required
def getStudentByRollNo(request):
    if request.method == 'GET':
        rollNo = request.GET['rollNo']
        student = Student.objects.get(rollnumber=rollNo)

        data = {
            'name': student.fullname,
            'fathername': student.fathername,
            'address': student.address,
            'pfp': student.pfp.url if student.pfp else None,
            'courses_applied': student.courses_applied
        }

        return JsonResponse(data)


def get_image_base64(image_path):
    with default_storage.open(image_path, 'rb') as img_file:
        return base64.b64encode(img_file.read()).decode('utf-8')

@login_required
def getReceipt(request):
    # return render(request, 'receipt.html')
    fee = Fee.objects.get(receipt_number=request.GET['receipt_number'])

    static_url = settings.STATIC_URL

    p = inflect.engine()

    this_folder = os.path.dirname(os.path.abspath(__file__))

    signature_path = 'file://' + os.path.join(this_folder, 'static', 'signature.jpg' )
    logo_path = 'file://' + os.path.join(this_folder, 'static', 'logo.png' )


    context = {
        'receipt_number': fee.receipt_number,
        'date': fee.deposit_date,
        'fees_amount_in_words': p.number_to_words(fee.fee_amount).capitalize() + ' only',
        'student_name': fee.student.fullname,
        'father_name': fee.student.fathername,
        'address': fee.student.address,
        'fees_amount': fee.fee_amount,
        'signature': signature_path,
        'logo': logo_path
    }


    html_string = render_to_string('receipt.html', context)
    pdf_file = HTML(string=html_string).write_pdf()
    
    response = HttpResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="document.pdf"'
    return response



@login_required
def getReceiptHTML(request):
    # return render(request, 'receipt.html')
    fee = Fee.objects.get(receipt_number=request.GET['receipt_number'])


    p = inflect.engine()


    context = {
        'receipt_number': fee.receipt_number,
        'date': fee.deposit_date,
        'fees_amount_in_words': p.number_to_words(fee.fee_amount).capitalize() + ' only',
        'student_name': fee.student.fullname,
        'father_name': fee.student.fathername,
        'address': fee.student.address,
        'fees_amount': fee.fee_amount,
    }


    html_string = render_to_string('receipt.html', context)
    
    response = HttpResponse(html_string)
    return response



@login_required
def updateStudent(request):
    if request.method=='POST':
        dob = request.POST['dob']

        class10_details = {
            "board": request.POST['board_x'],
            "percentage": request.POST['percentage_x'],
            "year_of_passing": request.POST['year_x']
        }
        class12_details = {
            "board": request.POST['board_xii'],
            "percentage": request.POST['percentage_xii'],
            "year_of_passing": request.POST['year_xii']
        }
        graduation_details = {
            "board": request.POST['board_graduation'],
            "percentage": request.POST['percentage_graduation'],
            "year_of_passing": request.POST['year_graduation']
        }
        masters_details = {
            "board": request.POST['board_masters'],
            "percentage": request.POST['percentage_masters'],
            "year_of_passing": request.POST['year_masters']
        }

        courses_applied = request.POST.getlist('courses')

        
        student = Student.objects.get(rollnumber=request.POST['roll_number'])
        student.fullname=request.POST['full_name']
        student.dob=dob
        student.email=request.POST['email']
        student.mobile_number=request.POST['mobile']
        student.gender=request.POST['gender']
        student.address=request.POST['address']
        student.fathername=request.POST['father_name']
        student.class10_details=class10_details
        student.class12_details=class12_details
        student.graduation_details=graduation_details
        student.masters_details=masters_details
        student.courses_applied=courses_applied
        if len(request.FILES)>0:
            pfp = request.FILES['photo']
            if pfp is not None:
                student.pfp = pfp

        student.save()

        return redirect(reverse('firstpage:list'))
    return JsonResponse({'message': 'Use post request'})


@login_required
def deleteStudent(request):
    if request.method=='POST':
        student = Student.objects.get(rollnumber=request.POST['roll_number'])
        student.delete()
        return redirect(reverse('firstpage:list'))
    return JsonResponse({'message': 'Use post request'})


@login_required
def searchFee(request):
    query = request.GET.get('q', '')
    results = []


    if query=='':
        print('n')
        students = Student.objects.all()


hotel/firstpage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Wittgenstein:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">

  {% block css %}{% endblock %}

  <style>

  .theTable{
    margin-left: 10%;

  }

  .theTable tr td{
    padding-bottom: 6px;
  }

  .imageBox{
    margin-left: -100px;
    margin-top: 100px;
  }


  body{
    font-family: "Wittgenstein", serif;
  }

    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 100%}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-image:url("{% static 'back.jpg' %}") ;
      height: 100%;
      font-size:20px;


    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }


    .sidenav{
      border-right: 1px solid gray;
     }


     .navlink{
      color: black;
     }


     .accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  text-align: left;
  border: none;
  outline: none;
  transition: 0.4s;
}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active, .accordion:hover {
  background-color: #ccc;
}

/* Style the accordion panel. Note: hidden by default */
.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
h3{
  font-family: Calibri;
  font-size: 25pt;
  font-style: normal;
  font-weight: bold;
  color:SlateBlue;
  text-align: center;
  text-decoration: underline
}

table{
  font-family: Calibri;
  color:black;
  font-size: 11pt;
  font-style: normal;
  font-weight: bold;

  border-collapse: collapse;

}
table.inner{
  border: 0px
}

.theBody{
max-height: 1000px;
}


/* Container for the news ticker */
.news-ticker-container {
    height: 400px; /* Adjust based on content height */
    overflow: hidden;
    position: relative;
    background: #f1f1f1; /* Background color for the ticker */
    border: 1px solid #ddd; /* Optional border */
}

/* The ticker itself */
.news-ticker {
    display: flex;
    flex-direction: column;
    animation: scroll-up 10s linear infinite;
    cursor: pointer;
}

.news-ticker:hover{
  animation-play-state: paused;
}

/* Individual news item styling */
.news-item {
    padding: 10px;
    background: #fff; /* Background color for each item */
    border-bottom: 1px solid #ddd; /* Optional border for separation */
    white-space: normal; /* Ensure text wraps within the div */
    word-wrap: break-word; /* Break long words and wrap text */
    overflow-wrap: break-word; /* Break long words and wrap text */
}

/* Animation to scroll the news items upwards */
@keyframes scroll-up {
    0% {
        transform: translateY(400px);
    }
    100% {
        transform: translateY(-100%);
    }
}

  </style>
</head>
<body background="{% static 'back.jpg' %}">

<div class="container-fluid">
  <div class="row content" style="height: 100%;">
    <div class="col-sm-3 sidenav" style="border: 20px solid #F5F5F5;"><br>
      <center><img src="{% static 'h3.jpg' %}" class="img-circle" height="100" width="106"  >
      <h4 class="site-name"> <p style="color:#660000;font-size:20px;"><b>GURU KRIPA INSTITUTION</b> </h4></center>
      <ul  class="nav nav-pills nav-stacked">
        <li class="{% if request.path == '/home/' %}active{% endif %}"><a href="{% url 'firstpage:index1'%}" class="navlink">Home</a></li>
        <li class="{% if request.path == '/course/' %}active{% endif %}"><a href="{% url 'firstpage:course'%}" class="navlink">Courses Details</a></li>
        <li class="{% if request.path == '/admission/' %}active{% endif %}"><a href="{% url 'firstpage:admission'%}" class="navlink">Admission Form</a></li>
        <!-- <li class="{% if request.path == '/fee/' %}active{% endif %}"><a href="{% url 'firstpage:fee'%}" class="navlink">Fee Deposit Window</a></li> -->
        <li class="{% if request.path == '/list/' %}active{% endif %}"><a href="{% url 'firstpage:list'%}" class="navlink">List of all Students</a></li>
        <!-- <li class="{% if request.path == '/fee_list/' %}active{% endif %}"><a href="{% url 'firstpage:feeList'%}" class="navlink">Fee Details of all the students</a></li> -->
        <li class="{% if request.path == '/employee_corner/' %}active{% endif %}"><a href="{% url 'firstpage:employeeCorner' %}" class="navlink">Employee Corner</a></li>
        <li class="{% if request.path == '/employee_attendance/' %}active{% endif %}"><a href="{% url 'firstpage:employeeAttendance' %}" class="navlink">Employee Attendance</a></li>
        <li class="{% if request.path == '/downloads/' %}active{% endif %}"><a href="{% url 'firstpage:downloads' %}" class="navlink">Downloads</a></li>
        <li class="{% if request.path == '/new_updates/' %}active{% endif %}"><a href="{% url 'firstpage:new_updates' %}" class="navlink">New Updates in the Institution</a></li>
        <li class="{% if request.path == '/logout/' %}active{% endif %}"><a href="{% url 'firstpage:logout' %}" class="navlink" style="color: red;">Logout</a></li>
      </ul><br>

      <div class="news-ticker-container">
        <div class="news-ticker">

            {% for new_update in base_new_updates %}
              <div class="news-item">{{new_update.description}}</div>
            {% endfor %}

        </div>
    </div>

    </div>


      {% block body %}

      {% endblock %}

  </div>
</div>

<footer class="container-fluid">
  <p>Guru Kripa Institution <br> Shaheed Naresh Chwok Sunder Nagar DIstt Mandi HP 175019 <br> Visit us at :www.gurukripainstitution.in </p>
</footer>

</>
</html>

hotel/firstpage/templates/downloads.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-9">
            <div class="well">
                <img src="{% static 'dd.jpg' %}" width="100%" height="80">
            </div>
            
            <div class="container">
                
                <div class="the-container">
                    <h1 style="text-align: center;">Downloads</h1>

                    <ul class="pdf-list">
                            <li>
                                <a href="{% static 'signature.jpg' %}" target="_blank" class="pdf-link">The Form</a>
                            </li>
                    </ul>
                </div>
            
            </div>
        </div>
    </div>
</div>

<style>
    .container{
        max-width: 1000px;
        margin: auto;
        background: white;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        min-height: 400px;
    }
    .downloads-title {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .pdf-list {
        list-style-type: none;
        padding: 0;
    }

    .pdf-list li {
        margin-bottom: 10px;
    }

    .pdf-link {
        text-decoration: none;
        color: #007bff; /* Bootstrap primary color */
        font-size: 18px;
        transition: color 0.3s ease;
    }

    .pdf-link:hover {
        color: #0056b3; /* Darker shade on hover */
        text-decoration: underline;
    }
</style>
{% endblock %}

hotel/firstpage/templates/fee_detail_list.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
    .container {
        max-width: 1000px;
        margin: auto;
        background: white;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th,
    td {
        padding: 12px;
        text-align: left;
        border: 1px solid #ddd;
    }

    tbody tr {
        cursor: pointer;
    }

    th {
        background-color: #f4f4f4;
    }

    tr:nth-child(even) {
        background-color: #f9f9f9;
    }

    .photo {
        width: 50px;
        height: 50px;
        object-fit: cover;
        border-radius: 50%;
    }

    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
        padding-top: 60px;
    }

    .modal-content {
        background-color: #fefefe;
        margin: 5% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        max-width: 700px;
        border-radius: 8px;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }


    .search-container {
        max-width: 600px;
        margin: 20px auto;
        padding: 0 10px;
        position: relative;
    }

    #search-input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 16px;
    }

    .results-container {
        margin-top: 10px;
    }

    .results-container div {
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        background-color: white;
        cursor: pointer;
    }

    .results-container div:hover {
        background-color: #f0f0f0;
    }
</style>
{% endblock css %}


{% block body %}

<div class="col-sm-9">

    <div class="well">
        <img src="{% static 'dd.jpg' %}" width="100%" height="80">

    </div><br>

    <div class="container">
        <h1>Fee Information</h1>


        <div class="search-container">
            <input type="text" id="search-input" placeholder="Search..." autocomplete="off">
            <div id="search-results" class="results-container"></div>
        </div>


        <table id="studentsTable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ROLL NUMBER</th>
                    <th>FULL NAME</th>
                    <th>EMAIL ID</th>
                    <th>DEPOSIT DATE</th>
                    <th>TOTAL AMOUNT</th>
                    <th>PHOTO</th>
                </tr>
            </thead>
            <tbody id="table-body">



                <!-- Repeat <tr> block for more students -->
            </tbody>
        </table>
    </div>
</div>


<!-- The Modal -->
<div id="studentModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Receipt</h2>
        <div id="modalBody">
            <!-- Details will be inserted here via JavaScript -->
        </div>
    </div>
</div>


<script>

    const feesListString = '{{fee_list|safe}}';
    const feesList = JSON.parse(feesListString);

    console.log(feesList)



    const table = document.getElementById('studentsTable');
    const modal = document.getElementById('studentModal');
    const closeBtn = document.querySelector('.close');
    const modalBody = document.getElementById('modalBody');


    const tableBody = document.getElementById('table-body');

    feesList.map((fee, index) => {
        tableBody.innerHTML += `<tr data-id="${fee.student.rollnumber}">
                                <td>${fee.receipt_number}</td>
                                <td>${fee.student.rollnumber}</td>
                                <td>${fee.student.fullname}</td>
                                <td>${fee.student.email}</td>
                                <td>${fee.deposit_date}</td>
                                <td>${fee.fee_amount}</td>
                                <td><img src="${fee.student.pfp ? fee.student.pfp : ''}" alt="John Doe" class="photo"></td>
                            </tr>`;
    })



    table.addEventListener('click', async (event) => {
        const row = event.target.closest('tr');
        if (row) {
            const id = row.getAttribute('data-id');
            const fee = feesList.find(s => s.student.rollnumber == id);

            const response = await fetch(`{% url 'firstpage:getReceiptHTML' %}?receipt_number=${fee.receipt_number}`)
            if(response.ok){
                const receiptHTML = await response.text();

                if (fee) {
    
                    modalBody.innerHTML = `
                            <div style="display: flex; flex-direction: column;">
                                <div onclick="location.href='/get_receipt?receipt_number=${fee.receipt_number}'" style="cursor: pointer; color: blue; margin-left: auto; margin-right: 10%;">Download Receipt</div>
                                ${receiptHTML}
                            </div>
                        `;
                    modal.style.display = 'block';
                }
            }

        }
    });

    closeBtn.onclick = () => {
        modal.style.display = 'none';
    }

    window.onclick = (event) => {
        if (event.target === modal) {
            modal.style.display = 'none';
        }
    }
</script>




<script>

document.addEventListener('DOMContentLoaded', function() {
    const searchInput = document.getElementById('search-input');
    const resultsContainer = document.getElementById('search-results');
    let debounceTimer;

    searchInput.addEventListener('input', function() {
        clearTimeout(debounceTimer);

        debounceTimer = setTimeout(() => {
            const query = searchInput.value.trim();

                fetch(`{% url 'firstpage:searchFee' %}?q=${encodeURIComponent(query)}`)
                    .then(response => response.json())
                    .then(data => {
                        displayResults(data);
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        resultsContainer.innerHTML = '<div>Error fetching results.</div>';
                    });
            
        }, 500); // 0.5 second debounce
    });

    function displayResults(data) {
        if (data.length > 0) {
            tableBody.innerHTML = data.map(fee =>`<tr data-id="${fee.rollnumber}">
                                <td>${fee.receipt_number}</td>
                                <td>${fee.rollnumber}</td>
                                <td>${fee.fullname}</td>
                                <td>${fee.email}</td>
                                <td>${fee.deposit_date}</td>
                                <td>${fee.fee_amount}</td>
                                <td><img src="${fee.pfp}" alt="John Doe" class="photo"></td>
                            </tr>`).join('');
            resultsContainer.innerHTML = ''
        } else {
            resultsContainer.innerHTML = '<div>No results found.</div>';
        }
    }
});

</script>



{% endblock body %}